// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go
//
// Generated by this command:
//
//	mockgen -source=delivery.go -destination=mock/delivery.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	webhook "github.com/sonymuhamad/webhook-lab"
	gomock "go.uber.org/mock/gomock"
)

// MockDeliveryUsecase is a mock of DeliveryUsecase interface.
type MockDeliveryUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryUsecaseMockRecorder
	isgomock struct{}
}

// MockDeliveryUsecaseMockRecorder is the mock recorder for MockDeliveryUsecase.
type MockDeliveryUsecaseMockRecorder struct {
	mock *MockDeliveryUsecase
}

// NewMockDeliveryUsecase creates a new mock instance.
func NewMockDeliveryUsecase(ctrl *gomock.Controller) *MockDeliveryUsecase {
	mock := &MockDeliveryUsecase{ctrl: ctrl}
	mock.recorder = &MockDeliveryUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryUsecase) EXPECT() *MockDeliveryUsecaseMockRecorder {
	return m.recorder
}

// ProcessDue mocks base method.
func (m *MockDeliveryUsecase) ProcessDue(ctx context.Context, limit int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessDue", ctx, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessDue indicates an expected call of ProcessDue.
func (mr *MockDeliveryUsecaseMockRecorder) ProcessDue(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDue", reflect.TypeOf((*MockDeliveryUsecase)(nil).ProcessDue), ctx, limit)
}

// MockDeliveryRepository is a mock of DeliveryRepository interface.
type MockDeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRepositoryMockRecorder
	isgomock struct{}
}

// MockDeliveryRepositoryMockRecorder is the mock recorder for MockDeliveryRepository.
type MockDeliveryRepositoryMockRecorder struct {
	mock *MockDeliveryRepository
}

// NewMockDeliveryRepository creates a new mock instance.
func NewMockDeliveryRepository(ctrl *gomock.Controller) *MockDeliveryRepository {
	mock := &MockDeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRepository) EXPECT() *MockDeliveryRepositoryMockRecorder {
	return m.recorder
}

// CreateAttempt mocks base method.
func (m *MockDeliveryRepository) CreateAttempt(ctx context.Context, param webhook.CreateAttemptParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttempt", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttempt indicates an expected call of CreateAttempt.
func (mr *MockDeliveryRepositoryMockRecorder) CreateAttempt(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttempt", reflect.TypeOf((*MockDeliveryRepository)(nil).CreateAttempt), ctx, param)
}

// CreateForActiveEndpoints mocks base method.
func (m *MockDeliveryRepository) CreateForActiveEndpoints(ctx context.Context, message webhook.Message) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForActiveEndpoints", ctx, message)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateForActiveEndpoints indicates an expected call of CreateForActiveEndpoints.
func (mr *MockDeliveryRepositoryMockRecorder) CreateForActiveEndpoints(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForActiveEndpoints", reflect.TypeOf((*MockDeliveryRepository)(nil).CreateForActiveEndpoints), ctx, message)
}

// ListAttempts mocks base method.
func (m *MockDeliveryRepository) ListAttempts(ctx context.Context, deliveryIDs []uuid.UUID) ([]webhook.Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttempts", ctx, deliveryIDs)
	ret0, _ := ret[0].([]webhook.Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttempts indicates an expected call of ListAttempts.
func (mr *MockDeliveryRepositoryMockRecorder) ListAttempts(ctx, deliveryIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttempts", reflect.TypeOf((*MockDeliveryRepository)(nil).ListAttempts), ctx, deliveryIDs)
}

// ListByMessage mocks base method.
func (m *MockDeliveryRepository) ListByMessage(ctx context.Context, messageID uuid.UUID) ([]webhook.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMessage", ctx, messageID)
	ret0, _ := ret[0].([]webhook.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMessage indicates an expected call of ListByMessage.
func (mr *MockDeliveryRepositoryMockRecorder) ListByMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMessage", reflect.TypeOf((*MockDeliveryRepository)(nil).ListByMessage), ctx, messageID)
}

// ListDue mocks base method.
func (m *MockDeliveryRepository) ListDue(ctx context.Context, limit int) ([]webhook.DueDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDue", ctx, limit)
	ret0, _ := ret[0].([]webhook.DueDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDue indicates an expected call of ListDue.
func (mr *MockDeliveryRepositoryMockRecorder) ListDue(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDue", reflect.TypeOf((*MockDeliveryRepository)(nil).ListDue), ctx, limit)
}

// Update mocks base method.
func (m *MockDeliveryRepository) Update(ctx context.Context, param webhook.UpdateDeliveryParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeliveryRepositoryMockRecorder) Update(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeliveryRepository)(nil).Update), ctx, param)
}

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockSender) Send(ctx context.Context, req webhook.SendRequest) (webhook.SendResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, req)
	ret0, _ := ret[0].(webhook.SendResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockSenderMockRecorder) Send(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSender)(nil).Send), ctx, req)
}
