// Code generated by MockGen. DO NOT EDIT.
// Source: endpoint.go
//
// Generated by this command:
//
//	mockgen -source=endpoint.go -destination=mock/endpoint.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	webhook "github.com/sonymuhamad/webhook-lab"
	gomock "go.uber.org/mock/gomock"
)

// MockEndpointUsecase is a mock of EndpointUsecase interface.
type MockEndpointUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointUsecaseMockRecorder
	isgomock struct{}
}

// MockEndpointUsecaseMockRecorder is the mock recorder for MockEndpointUsecase.
type MockEndpointUsecaseMockRecorder struct {
	mock *MockEndpointUsecase
}

// NewMockEndpointUsecase creates a new mock instance.
func NewMockEndpointUsecase(ctrl *gomock.Controller) *MockEndpointUsecase {
	mock := &MockEndpointUsecase{ctrl: ctrl}
	mock.recorder = &MockEndpointUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointUsecase) EXPECT() *MockEndpointUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEndpointUsecase) Create(ctx context.Context, param webhook.CreateEndpointParam) (webhook.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, param)
	ret0, _ := ret[0].(webhook.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEndpointUsecaseMockRecorder) Create(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEndpointUsecase)(nil).Create), ctx, param)
}

// List mocks base method.
func (m *MockEndpointUsecase) List(ctx context.Context, param webhook.ListEndpointsParam) (webhook.ListEndpointsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, param)
	ret0, _ := ret[0].(webhook.ListEndpointsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEndpointUsecaseMockRecorder) List(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEndpointUsecase)(nil).List), ctx, param)
}

// MockEndpointRepository is a mock of EndpointRepository interface.
type MockEndpointRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointRepositoryMockRecorder
	isgomock struct{}
}

// MockEndpointRepositoryMockRecorder is the mock recorder for MockEndpointRepository.
type MockEndpointRepositoryMockRecorder struct {
	mock *MockEndpointRepository
}

// NewMockEndpointRepository creates a new mock instance.
func NewMockEndpointRepository(ctrl *gomock.Controller) *MockEndpointRepository {
	mock := &MockEndpointRepository{ctrl: ctrl}
	mock.recorder = &MockEndpointRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointRepository) EXPECT() *MockEndpointRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEndpointRepository) Create(ctx context.Context, param webhook.CreateEndpointParam) (webhook.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, param)
	ret0, _ := ret[0].(webhook.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEndpointRepositoryMockRecorder) Create(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEndpointRepository)(nil).Create), ctx, param)
}

// ListByTenant mocks base method.
func (m *MockEndpointRepository) ListByTenant(ctx context.Context, param webhook.ListEndpointsParam) (webhook.ListEndpointsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenant", ctx, param)
	ret0, _ := ret[0].(webhook.ListEndpointsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenant indicates an expected call of ListByTenant.
func (mr *MockEndpointRepositoryMockRecorder) ListByTenant(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenant", reflect.TypeOf((*MockEndpointRepository)(nil).ListByTenant), ctx, param)
}
