// Code generated by MockGen. DO NOT EDIT.
// Source: tenant.go
//
// Generated by this command:
//
//	mockgen -source=tenant.go -destination=mock/tenant.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	webhook "github.com/sonymuhamad/webhook-lab"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantUsecase is a mock of TenantUsecase interface.
type MockTenantUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockTenantUsecaseMockRecorder
	isgomock struct{}
}

// MockTenantUsecaseMockRecorder is the mock recorder for MockTenantUsecase.
type MockTenantUsecaseMockRecorder struct {
	mock *MockTenantUsecase
}

// NewMockTenantUsecase creates a new mock instance.
func NewMockTenantUsecase(ctrl *gomock.Controller) *MockTenantUsecase {
	mock := &MockTenantUsecase{ctrl: ctrl}
	mock.recorder = &MockTenantUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantUsecase) EXPECT() *MockTenantUsecaseMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockTenantUsecase) Authenticate(ctx context.Context, apiKey string) (webhook.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, apiKey)
	ret0, _ := ret[0].(webhook.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockTenantUsecaseMockRecorder) Authenticate(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockTenantUsecase)(nil).Authenticate), ctx, apiKey)
}

// Create mocks base method.
func (m *MockTenantUsecase) Create(ctx context.Context, param webhook.CreateTenantParam) (webhook.CreateTenantResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, param)
	ret0, _ := ret[0].(webhook.CreateTenantResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTenantUsecaseMockRecorder) Create(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantUsecase)(nil).Create), ctx, param)
}

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantRepository) Create(ctx context.Context, name string) (webhook.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(webhook.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTenantRepositoryMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantRepository)(nil).Create), ctx, name)
}

// CreateAPIKey mocks base method.
func (m *MockTenantRepository) CreateAPIKey(ctx context.Context, param webhook.CreateAPIKeyParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIKey", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAPIKey indicates an expected call of CreateAPIKey.
func (mr *MockTenantRepositoryMockRecorder) CreateAPIKey(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKey", reflect.TypeOf((*MockTenantRepository)(nil).CreateAPIKey), ctx, param)
}

// GetByAPIKeyHash mocks base method.
func (m *MockTenantRepository) GetByAPIKeyHash(ctx context.Context, hash []byte) (webhook.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAPIKeyHash", ctx, hash)
	ret0, _ := ret[0].(webhook.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAPIKeyHash indicates an expected call of GetByAPIKeyHash.
func (mr *MockTenantRepositoryMockRecorder) GetByAPIKeyHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAPIKeyHash", reflect.TypeOf((*MockTenantRepository)(nil).GetByAPIKeyHash), ctx, hash)
}

// NameExists mocks base method.
func (m *MockTenantRepository) NameExists(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NameExists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NameExists indicates an expected call of NameExists.
func (mr *MockTenantRepositoryMockRecorder) NameExists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NameExists", reflect.TypeOf((*MockTenantRepository)(nil).NameExists), ctx, name)
}
