// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package enum

import (
	"fmt"
	"strings"
)

const (
	// ClaimModeNaive is a ClaimMode of type naive.
	ClaimModeNaive ClaimMode = "naive"
	// ClaimModeSkiplocked is a ClaimMode of type skiplocked.
	ClaimModeSkiplocked ClaimMode = "skiplocked"
)

var ErrInvalidClaimMode = fmt.Errorf("not a valid ClaimMode, try [%s]", strings.Join(_ClaimModeNames, ", "))

var _ClaimModeNames = []string{
	string(ClaimModeNaive),
	string(ClaimModeSkiplocked),
}

// ClaimModeNames returns a list of possible string values of ClaimMode.
func ClaimModeNames() []string {
	tmp := make([]string, len(_ClaimModeNames))
	copy(tmp, _ClaimModeNames)
	return tmp
}

// String implements the Stringer interface.
func (x ClaimMode) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClaimMode) IsValid() bool {
	_, err := ParseClaimMode(string(x))
	return err == nil
}

var _ClaimModeValue = map[string]ClaimMode{
	"naive":      ClaimModeNaive,
	"skiplocked": ClaimModeSkiplocked,
}

// ParseClaimMode attempts to convert a string to a ClaimMode.
func ParseClaimMode(name string) (ClaimMode, error) {
	if x, ok := _ClaimModeValue[name]; ok {
		return x, nil
	}
	return ClaimMode(""), fmt.Errorf("%s is %w", name, ErrInvalidClaimMode)
}

// MarshalText implements the text marshaller method.
func (x ClaimMode) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ClaimMode) UnmarshalText(text []byte) error {
	tmp, err := ParseClaimMode(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x ClaimMode) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
