// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package enum

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// DeliveryStatusPending is a DeliveryStatus of type pending.
	DeliveryStatusPending DeliveryStatus = "pending"
	// DeliveryStatusSucceeded is a DeliveryStatus of type succeeded.
	DeliveryStatusSucceeded DeliveryStatus = "succeeded"
	// DeliveryStatusFailed is a DeliveryStatus of type failed.
	DeliveryStatusFailed DeliveryStatus = "failed"
)

var ErrInvalidDeliveryStatus = fmt.Errorf("not a valid DeliveryStatus, try [%s]", strings.Join(_DeliveryStatusNames, ", "))

var _DeliveryStatusNames = []string{
	string(DeliveryStatusPending),
	string(DeliveryStatusSucceeded),
	string(DeliveryStatusFailed),
}

// DeliveryStatusNames returns a list of possible string values of DeliveryStatus.
func DeliveryStatusNames() []string {
	tmp := make([]string, len(_DeliveryStatusNames))
	copy(tmp, _DeliveryStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x DeliveryStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DeliveryStatus) IsValid() bool {
	_, err := ParseDeliveryStatus(string(x))
	return err == nil
}

var _DeliveryStatusValue = map[string]DeliveryStatus{
	"pending":   DeliveryStatusPending,
	"succeeded": DeliveryStatusSucceeded,
	"failed":    DeliveryStatusFailed,
}

// ParseDeliveryStatus attempts to convert a string to a DeliveryStatus.
func ParseDeliveryStatus(name string) (DeliveryStatus, error) {
	if x, ok := _DeliveryStatusValue[name]; ok {
		return x, nil
	}
	return DeliveryStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidDeliveryStatus)
}

// MarshalText implements the text marshaller method.
func (x DeliveryStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *DeliveryStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseDeliveryStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x DeliveryStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errDeliveryStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *DeliveryStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = DeliveryStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseDeliveryStatus(v)
	case []byte:
		*x, err = ParseDeliveryStatus(string(v))
	case DeliveryStatus:
		*x = v
	case *DeliveryStatus:
		if v == nil {
			return errDeliveryStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errDeliveryStatusNilPtr
		}
		*x, err = ParseDeliveryStatus(*v)
	default:
		return errors.New("invalid type for DeliveryStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x DeliveryStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
