// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sonymuhamad/webhook-lab/enum"
)

const createAttempt = `-- name: CreateAttempt :exec
INSERT INTO attempts (delivery_id, tenant_id, status_code, error, duration_ms)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAttemptParams struct {
	DeliveryID uuid.UUID
	TenantID   uuid.UUID
	StatusCode *int32
	Error      *string
	DurationMs int32
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) error {
	_, err := q.db.Exec(ctx, createAttempt,
		arg.DeliveryID,
		arg.TenantID,
		arg.StatusCode,
		arg.Error,
		arg.DurationMs,
	)
	return err
}

const createDeliveriesForMessage = `-- name: CreateDeliveriesForMessage :execrows
INSERT INTO deliveries (message_id, endpoint_id, tenant_id)
SELECT $1::uuid, e.id, e.tenant_id
FROM endpoints e
WHERE e.tenant_id = $2::uuid
  AND e.disabled_at IS NULL
`

type CreateDeliveriesForMessageParams struct {
	MessageID uuid.UUID
	TenantID  uuid.UUID
}

func (q *Queries) CreateDeliveriesForMessage(ctx context.Context, arg CreateDeliveriesForMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, createDeliveriesForMessage, arg.MessageID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAttemptsByDeliveries = `-- name: ListAttemptsByDeliveries :many
SELECT id, delivery_id, status_code, error, duration_ms, created_at
FROM attempts
WHERE delivery_id = ANY($1::uuid[])
ORDER BY id
`

type ListAttemptsByDeliveriesRow struct {
	ID         uuid.UUID
	DeliveryID uuid.UUID
	StatusCode *int32
	Error      *string
	DurationMs int32
	CreatedAt  time.Time
}

func (q *Queries) ListAttemptsByDeliveries(ctx context.Context, deliveryIds []uuid.UUID) ([]ListAttemptsByDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listAttemptsByDeliveries, deliveryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttemptsByDeliveriesRow{}
	for rows.Next() {
		var i ListAttemptsByDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.StatusCode,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByMessage = `-- name: ListDeliveriesByMessage :many
SELECT d.id, d.message_id, d.endpoint_id, e.url AS endpoint_url, d.status,
       d.attempt_count, d.next_attempt_at, d.created_at, d.updated_at
FROM deliveries d
JOIN endpoints e ON e.id = d.endpoint_id
WHERE d.message_id = $1
ORDER BY d.id
`

type ListDeliveriesByMessageRow struct {
	ID            uuid.UUID
	MessageID     uuid.UUID
	EndpointID    uuid.UUID
	EndpointURL   string
	Status        enum.DeliveryStatus
	AttemptCount  int32
	NextAttemptAt time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListDeliveriesByMessage(ctx context.Context, messageID uuid.UUID) ([]ListDeliveriesByMessageRow, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveriesByMessageRow{}
	for rows.Next() {
		var i ListDeliveriesByMessageRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.EndpointID,
			&i.EndpointURL,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDeliveries = `-- name: ListDueDeliveries :many
SELECT d.id, d.message_id, d.tenant_id, d.attempt_count,
       e.url AS endpoint_url, m.event_type, m.payload
FROM deliveries d
JOIN endpoints e ON e.id = d.endpoint_id
JOIN messages m ON m.id = d.message_id
WHERE d.status = 'pending'
  AND d.next_attempt_at <= now()
ORDER BY d.next_attempt_at
LIMIT $1
`

type ListDueDeliveriesRow struct {
	ID           uuid.UUID
	MessageID    uuid.UUID
	TenantID     uuid.UUID
	AttemptCount int32
	EndpointURL  string
	EventType    string
	Payload      json.RawMessage
}

// The status filter is a literal, not a parameter, so the planner can match
// it to the partial index deliveries_due_idx.
//
// No row locks: two workers running this at once claim the same rows and
// send them twice. Lab 1 measures that before switching to SKIP LOCKED.
func (q *Queries) ListDueDeliveries(ctx context.Context, limit int32) ([]ListDueDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listDueDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueDeliveriesRow{}
	for rows.Next() {
		var i ListDueDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.TenantID,
			&i.AttemptCount,
			&i.EndpointURL,
			&i.EventType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryAfterAttempt = `-- name: UpdateDeliveryAfterAttempt :exec
UPDATE deliveries
SET status          = $2,
    attempt_count   = attempt_count + 1,
    next_attempt_at = $3,
    updated_at      = now()
WHERE id = $1
`

type UpdateDeliveryAfterAttemptParams struct {
	ID            uuid.UUID
	Status        enum.DeliveryStatus
	NextAttemptAt time.Time
}

func (q *Queries) UpdateDeliveryAfterAttempt(ctx context.Context, arg UpdateDeliveryAfterAttemptParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryAfterAttempt, arg.ID, arg.Status, arg.NextAttemptAt)
	return err
}
