// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sonymuhamad/webhook-lab/enum"
)

const claimDueDeliveries = `-- name: ClaimDueDeliveries :many
WITH due AS MATERIALIZED (
    SELECT id
    FROM deliveries
    WHERE status = 'pending'
      AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
), claimed AS (
    UPDATE deliveries d
    SET next_attempt_at = now() + make_interval(secs => $2::float8),
        updated_at      = now()
    FROM due
    WHERE d.id = due.id
    RETURNING d.id, d.message_id, d.endpoint_id, d.tenant_id, d.attempt_count
)
SELECT c.id, c.message_id, c.tenant_id, c.endpoint_id, c.attempt_count,
       e.url AS endpoint_url, m.event_type, m.payload, m.created_at AS message_created_at
FROM claimed c
JOIN endpoints e ON e.id = c.endpoint_id
JOIN messages m ON m.id = c.message_id
`

type ClaimDueDeliveriesParams struct {
	BatchSize    int32
	LeaseSeconds float64
}

type ClaimDueDeliveriesRow struct {
	ID               uuid.UUID
	MessageID        uuid.UUID
	TenantID         uuid.UUID
	EndpointID       uuid.UUID
	AttemptCount     int32
	EndpointURL      string
	EventType        string
	Payload          json.RawMessage
	MessageCreatedAt time.Time
}

// Claims due deliveries by pushing next_attempt_at forward by the lease, so
// other workers stop seeing them as due until the lease runs out.
//
// SKIP LOCKED only covers the moment of claiming: concurrent claims pass over
// rows another claim is taking instead of waiting for it. The row locks end
// when this statement commits, before anything is sent; from then on the
// lease is what keeps other workers away.
//
// MATERIALIZED makes Postgres run the locking select once, as its own step.
// Without it, Postgres 12+ may inline a CTE referenced once into the UPDATE,
// and a planner that rescans it could lock more rows than the batch size.
// Returned rows are in no particular order.
func (q *Queries) ClaimDueDeliveries(ctx context.Context, arg ClaimDueDeliveriesParams) ([]ClaimDueDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimDueDeliveries, arg.BatchSize, arg.LeaseSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueDeliveriesRow{}
	for rows.Next() {
		var i ClaimDueDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.TenantID,
			&i.EndpointID,
			&i.AttemptCount,
			&i.EndpointURL,
			&i.EventType,
			&i.Payload,
			&i.MessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDueDeliveriesFair = `-- name: ClaimDueDeliveriesFair :many
WITH candidates AS (
    SELECT d.id, d.next_attempt_at, d.turn
    FROM tenants t
    CROSS JOIN LATERAL (
        SELECT id, next_attempt_at, row_number() OVER (ORDER BY next_attempt_at) AS turn
        FROM deliveries
        WHERE tenant_id = t.id
          AND status = 'pending'
          AND next_attempt_at <= now()
        ORDER BY next_attempt_at
        LIMIT $1
    ) d
), due AS MATERIALIZED (
    SELECT d.id
    FROM deliveries d
    JOIN candidates c ON c.id = d.id
    WHERE d.status = 'pending'
      AND d.next_attempt_at <= now()
    ORDER BY c.turn, c.next_attempt_at
    LIMIT $2
    FOR UPDATE OF d SKIP LOCKED
), claimed AS (
    UPDATE deliveries d
    SET next_attempt_at = now() + make_interval(secs => $3::float8),
        updated_at      = now()
    FROM due
    WHERE d.id = due.id
    RETURNING d.id, d.message_id, d.endpoint_id, d.tenant_id, d.attempt_count
)
SELECT c.id, c.message_id, c.tenant_id, c.endpoint_id, c.attempt_count,
       e.url AS endpoint_url, m.event_type, m.payload, m.created_at AS message_created_at
FROM claimed c
JOIN endpoints e ON e.id = c.endpoint_id
JOIN messages m ON m.id = c.message_id
`

type ClaimDueDeliveriesFairParams struct {
	PerTenant    int32
	BatchSize    int32
	LeaseSeconds float64
}

type ClaimDueDeliveriesFairRow struct {
	ID               uuid.UUID
	MessageID        uuid.UUID
	TenantID         uuid.UUID
	EndpointID       uuid.UUID
	AttemptCount     int32
	EndpointURL      string
	EventType        string
	Payload          json.RawMessage
	MessageCreatedAt time.Time
}

// Like ClaimDueDeliveries, but takes the batch from the tenants in turns:
// every tenant's oldest due delivery first, then every tenant's second, and
// so on. A tenant with a large backlog then gets one slot per turn instead
// of the whole batch.
//
// candidates reads at most @per_tenant rows per tenant through
// deliveries_due_by_tenant_idx, so its cost grows with the number of tenants,
// not with the size of the backlog. It takes no locks: the outer select locks
// the chosen rows and skips any that another claim holds, then fills the
// batch from the next candidates. @per_tenant must therefore exceed the batch
// size, or concurrent claims on a single busy tenant come back short.
func (q *Queries) ClaimDueDeliveriesFair(ctx context.Context, arg ClaimDueDeliveriesFairParams) ([]ClaimDueDeliveriesFairRow, error) {
	rows, err := q.db.Query(ctx, claimDueDeliveriesFair, arg.PerTenant, arg.BatchSize, arg.LeaseSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueDeliveriesFairRow{}
	for rows.Next() {
		var i ClaimDueDeliveriesFairRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.TenantID,
			&i.EndpointID,
			&i.AttemptCount,
			&i.EndpointURL,
			&i.EventType,
			&i.Payload,
			&i.MessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingDeliveries = `-- name: CountPendingDeliveries :one
SELECT count(*) FILTER (WHERE next_attempt_at <= now()) AS due,
       count(*) FILTER (WHERE next_attempt_at > now())  AS scheduled
FROM deliveries
WHERE status = 'pending'
`

type CountPendingDeliveriesRow struct {
	Due       int64
	Scheduled int64
}

func (q *Queries) CountPendingDeliveries(ctx context.Context) (CountPendingDeliveriesRow, error) {
	row := q.db.QueryRow(ctx, countPendingDeliveries)
	var i CountPendingDeliveriesRow
	err := row.Scan(&i.Due, &i.Scheduled)
	return i, err
}

const createAttempt = `-- name: CreateAttempt :exec
INSERT INTO attempts (delivery_id, tenant_id, status_code, error, duration_ms)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAttemptParams struct {
	DeliveryID uuid.UUID
	TenantID   uuid.UUID
	StatusCode *int32
	Error      *string
	DurationMs int32
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) error {
	_, err := q.db.Exec(ctx, createAttempt,
		arg.DeliveryID,
		arg.TenantID,
		arg.StatusCode,
		arg.Error,
		arg.DurationMs,
	)
	return err
}

const createDeliveriesForMessage = `-- name: CreateDeliveriesForMessage :execrows
INSERT INTO deliveries (message_id, endpoint_id, tenant_id)
SELECT $1::uuid, e.id, e.tenant_id
FROM endpoints e
WHERE e.tenant_id = $2::uuid
  AND e.disabled_at IS NULL
`

type CreateDeliveriesForMessageParams struct {
	MessageID uuid.UUID
	TenantID  uuid.UUID
}

func (q *Queries) CreateDeliveriesForMessage(ctx context.Context, arg CreateDeliveriesForMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, createDeliveriesForMessage, arg.MessageID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAttemptsByDeliveries = `-- name: ListAttemptsByDeliveries :many
SELECT id, delivery_id, status_code, error, duration_ms, created_at
FROM attempts
WHERE delivery_id = ANY($1::uuid[])
ORDER BY id
`

type ListAttemptsByDeliveriesRow struct {
	ID         uuid.UUID
	DeliveryID uuid.UUID
	StatusCode *int32
	Error      *string
	DurationMs int32
	CreatedAt  time.Time
}

func (q *Queries) ListAttemptsByDeliveries(ctx context.Context, deliveryIds []uuid.UUID) ([]ListAttemptsByDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listAttemptsByDeliveries, deliveryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttemptsByDeliveriesRow{}
	for rows.Next() {
		var i ListAttemptsByDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.StatusCode,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByMessage = `-- name: ListDeliveriesByMessage :many
SELECT d.id, d.message_id, d.endpoint_id, e.url AS endpoint_url, d.status,
       d.attempt_count, d.next_attempt_at, d.created_at, d.updated_at
FROM deliveries d
JOIN endpoints e ON e.id = d.endpoint_id
WHERE d.message_id = $1
ORDER BY d.id
`

type ListDeliveriesByMessageRow struct {
	ID            uuid.UUID
	MessageID     uuid.UUID
	EndpointID    uuid.UUID
	EndpointURL   string
	Status        enum.DeliveryStatus
	AttemptCount  int32
	NextAttemptAt time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListDeliveriesByMessage(ctx context.Context, messageID uuid.UUID) ([]ListDeliveriesByMessageRow, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveriesByMessageRow{}
	for rows.Next() {
		var i ListDeliveriesByMessageRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.EndpointID,
			&i.EndpointURL,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDeliveries = `-- name: ListDueDeliveries :many
SELECT d.id, d.message_id, d.tenant_id, d.endpoint_id, d.attempt_count,
       e.url AS endpoint_url, m.event_type, m.payload, m.created_at AS message_created_at
FROM deliveries d
JOIN endpoints e ON e.id = d.endpoint_id
JOIN messages m ON m.id = d.message_id
WHERE d.status = 'pending'
  AND d.next_attempt_at <= now()
ORDER BY d.next_attempt_at
LIMIT $1
`

type ListDueDeliveriesRow struct {
	ID               uuid.UUID
	MessageID        uuid.UUID
	TenantID         uuid.UUID
	EndpointID       uuid.UUID
	AttemptCount     int32
	EndpointURL      string
	EventType        string
	Payload          json.RawMessage
	MessageCreatedAt time.Time
}

// The status filter is a literal, not a parameter, so the planner can match
// it to the partial index deliveries_due_idx.
//
// No row locks and no lease: workers running this at once read the same rows
// and all send them. Used only by CLAIM_MODE=naive, for lab 01.
func (q *Queries) ListDueDeliveries(ctx context.Context, limit int32) ([]ListDueDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listDueDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueDeliveriesRow{}
	for rows.Next() {
		var i ListDueDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.TenantID,
			&i.EndpointID,
			&i.AttemptCount,
			&i.EndpointURL,
			&i.EventType,
			&i.Payload,
			&i.MessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postponeDelivery = `-- name: PostponeDelivery :exec
UPDATE deliveries
SET next_attempt_at = $2,
    updated_at      = now()
WHERE id = $1
  AND status = 'pending'
`

type PostponeDeliveryParams struct {
	ID            uuid.UUID
	NextAttemptAt time.Time
}

// Hands a claimed delivery back without an attempt: it becomes due again at
// next_attempt_at and keeps its attempt count.
func (q *Queries) PostponeDelivery(ctx context.Context, arg PostponeDeliveryParams) error {
	_, err := q.db.Exec(ctx, postponeDelivery, arg.ID, arg.NextAttemptAt)
	return err
}

const updateDeliveryAfterAttempt = `-- name: UpdateDeliveryAfterAttempt :exec
UPDATE deliveries
SET status          = $2,
    attempt_count   = attempt_count + 1,
    next_attempt_at = $3,
    updated_at      = now()
WHERE id = $1
`

type UpdateDeliveryAfterAttemptParams struct {
	ID            uuid.UUID
	Status        enum.DeliveryStatus
	NextAttemptAt time.Time
}

func (q *Queries) UpdateDeliveryAfterAttempt(ctx context.Context, arg UpdateDeliveryAfterAttemptParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryAfterAttempt, arg.ID, arg.Status, arg.NextAttemptAt)
	return err
}
