// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoint.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countEndpointsByTenant = `-- name: CountEndpointsByTenant :one
SELECT count(*)
FROM endpoints
WHERE tenant_id = $1
  AND disabled_at IS NULL
`

func (q *Queries) CountEndpointsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpointsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (tenant_id, url)
VALUES ($1, $2)
RETURNING id, tenant_id, url, created_at
`

type CreateEndpointParams struct {
	TenantID uuid.UUID
	URL      string
}

type CreateEndpointRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	URL       string
	CreatedAt time.Time
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (CreateEndpointRow, error) {
	row := q.db.QueryRow(ctx, createEndpoint, arg.TenantID, arg.URL)
	var i CreateEndpointRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.URL,
		&i.CreatedAt,
	)
	return i, err
}

const listEndpointsByTenant = `-- name: ListEndpointsByTenant :many
SELECT id, tenant_id, url, created_at
FROM endpoints
WHERE tenant_id = $1
  AND disabled_at IS NULL
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListEndpointsByTenantParams struct {
	TenantID uuid.UUID
	Limit    int32
	Offset   int32
}

type ListEndpointsByTenantRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	URL       string
	CreatedAt time.Time
}

func (q *Queries) ListEndpointsByTenant(ctx context.Context, arg ListEndpointsByTenantParams) ([]ListEndpointsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listEndpointsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEndpointsByTenantRow{}
	for rows.Next() {
		var i ListEndpointsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.URL,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
