// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (tenant_id, event_type, payload, idempotency_key)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
RETURNING id, tenant_id, event_type, payload, idempotency_key, created_at
`

type CreateMessageParams struct {
	TenantID       uuid.UUID
	EventType      string
	Payload        json.RawMessage
	IdempotencyKey *string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.TenantID,
		arg.EventType,
		arg.Payload,
		arg.IdempotencyKey,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, tenant_id, event_type, payload, idempotency_key, created_at
FROM messages
WHERE id = $1
  AND tenant_id = $2
`

type GetMessageParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.ID, arg.TenantID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByIdempotencyKey = `-- name: GetMessageByIdempotencyKey :one
SELECT id, tenant_id, event_type, payload, idempotency_key, created_at
FROM messages
WHERE tenant_id = $1
  AND idempotency_key = $2
`

type GetMessageByIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	IdempotencyKey *string
}

func (q *Queries) GetMessageByIdempotencyKey(ctx context.Context, arg GetMessageByIdempotencyKeyParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}
