// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sonymuhamad/webhook-lab/enum"
)

type APIKey struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	KeyHash   []byte
	Prefix    string
	CreatedAt time.Time
	RevokedAt *time.Time
}

type Attempt struct {
	ID         uuid.UUID
	DeliveryID uuid.UUID
	TenantID   uuid.UUID
	StatusCode *int32
	Error      *string
	DurationMs int32
	CreatedAt  time.Time
}

type Delivery struct {
	ID            uuid.UUID
	MessageID     uuid.UUID
	EndpointID    uuid.UUID
	TenantID      uuid.UUID
	Status        enum.DeliveryStatus
	AttemptCount  int32
	NextAttemptAt time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Endpoint struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	URL        string
	CreatedAt  time.Time
	DisabledAt *time.Time
}

type Message struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	EventType      string
	Payload        json.RawMessage
	IdempotencyKey *string
	CreatedAt      time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}
