// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (tenant_id, key_hash, prefix)
VALUES ($1, $2, $3)
`

type CreateAPIKeyParams struct {
	TenantID uuid.UUID
	KeyHash  []byte
	Prefix   string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey, arg.TenantID, arg.KeyHash, arg.Prefix)
	return err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTenantByAPIKeyHash = `-- name: GetTenantByAPIKeyHash :one
SELECT t.id, t.name, t.created_at
FROM tenants t
JOIN api_keys k ON k.tenant_id = t.id
WHERE k.key_hash = $1
  AND k.revoked_at IS NULL
`

func (q *Queries) GetTenantByAPIKeyHash(ctx context.Context, keyHash []byte) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByAPIKeyHash, keyHash)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
