// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/sonymuhamad/webhook-lab/config"
	"github.com/sonymuhamad/webhook-lab/httpapi"
	"github.com/sonymuhamad/webhook-lab/postgres"
	"net/http"
)

// Injectors from wire.go:

func InitAPI(ctx context.Context, cfg config.Config) (*http.Server, func(), error) {
	configHTTP := cfg.HTTP
	configPostgres := cfg.Postgres
	pool, cleanup, err := postgres.NewPool(ctx, configPostgres)
	if err != nil {
		return nil, nil, err
	}
	handler := httpapi.NewRouter(pool)
	server := httpapi.NewServer(configHTTP, handler)
	return server, func() {
		cleanup()
	}, nil
}
